### ISSUE TITLE
Unloading cheat

### ISSUE THREAD

**Issue by mubuj** [EternityX/DEADCELL-CSGO#26] opened 2019-03-22 07:01 UTC
Correct unloading of cheat, after the discharge can no longer be Sangachal without rejoining the game

**Comment by alpine971** [comment] 2019-03-22 07:01
what

**Comment by mubuj** [comment] 2019-03-22 07:13
@alpine971 You can't read?You are told that after pressing END cheat is unloaded from the game and can not re-inject

**Comment by mubuj** [comment] 2019-03-22 07:14
![image](https://user-images.githubusercontent.com/48820838/54806514-439c6980-4c8b-11e9-92ce-497dc14b1e77.png)

**Comment by alpine971** [comment] 2019-03-22 07:16
What you said in the issue isn’t a proper english sentence(s), when you unload you have to close your game and inject again, I’ll fix it in a later update.

**Comment by mubuj** [comment] 2019-03-22 07:19
All free pa$te already there unloading

**Comment by EternityX** [comment] 2019-03-22 07:54
Unloading will be fixed. 
If you want it faster, perhaps you can it add yourself by using the 'pa$te'

**Closed by EternityX** 2019-03-22 07:54 UTC
Labels: bug
